# This file will be used for production-use only. 

version: '3.9'
services:
 node:
    image: node:alpine
    container_name: shooter-io-node-server
    ports:
    - '8080:8080'
    volumes:
    - ./server:/app
    working_dir: /app
    command: ["node", "index.js"]