name: Deployment

on: [workflow_dispatch]

jobs:
  lifecycle:
    runs-on: ubuntu-latest

    steps:
    - name: Download client and server artifacts
      uses: actions/download-artifact@v4

    - name: Setup Private Key
      run: |
        echo "SSH_PRIVATE_KEY" > temp_key
        chmod 600 temp_key
      env:
        SSH_PRIVATE_KEY: ${{secrets.DEPLOYMENT_PK}}

    - name: Deploy server artifact to production server
      run: |
        scp -i temp_key -r server root@217.160.53.253:/data/stacks/shooter-io-server

    - name: Deploy client artifact to production server
      run: |
        scp -i temp_key -r client root@217.160.53.253:/data/stacks/shooter-io-client
    
    - name: Clean up temp files
      run: rm temp_key

    