name: Deployment

on: [workflow_dispatch]

jobs:
  lifecycle:
    runs-on: ubuntu-latest

    steps:
    - name: Download client artifact
      uses: actions/download-artifact@v4
      with:
        name: client
        run-id: ${{ github.event.workflow_run.id }}

    - name: Download client artifact
      uses: actions/download-artifact@v4
      with:
        name: server
        run-id: ${{ github.event.workflow_run.id }}

    - name: Output folder structure
      run: ls -R -a

    - name: Setup Private Key
      run: |
        echo "${{secrets.DEPLOYMENT_PK}}" > temp_key
        chmod 600 temp_key

    - name: Deploy server artifact to production server
      run: |
        scp -o StrictHostKeyChecking=no -v -i temp_key -r server root@217.160.53.253:/data/stacks/shooter-io-server

    - name: Deploy client artifact to production server
      run: |
        scp -o StrictHostKeyChecking=no -v -i temp_key -r client root@217.160.53.253:/data/stacks/shooter-io-client
    
    - name: Clean up temp files
      run: rm temp_key

    