name: Project Lifecycle

on:
  push:
    branches:
      - '*'

jobs:
  lifecycle:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm ci

    - name: Audit depencdencies
      run: npm audit

    # Server Pipeline

    - name: Server - Lint
      run: npm run lint
      working-directory: server

    - name: Server - Test
      run: npm run test --if-present
      working-directory: server

    - name: Server - Build
      run: npm run build
      working-directory: server

    - name: Store server artifact
      uses: actions/upload-artifact@v4
      with:
        name: server
        path: server/dist

    # Client Pipeline

    - name: Client - Lint
      run: npm run lint
      working-directory: client

    - name: Client - Test
      run: npm run test --if-present
      working-directory: client

    - name: Client - Build
      run: npm run build
      working-directory: client
    
    - name: Store client artifact
      uses: actions/upload-artifact@v4
      with:
        name: client
        path: client/dist

    # Shared Pipeline

    - name: Shared - Lint
      run: npm run lint
      working-directory: shared

    - name: Shared - Test
      run: npm run test --if-present
      working-directory: shared

    - name: Trigger deployment workflow
      if: github.ref == 'refs/heads/main'
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: Deployment
        # On credentials issues: Remember that the token will be invalidated after a specific time period
        token: ${{ secrets.PAT }}