name: Client Workflow

on:
  push:
    branches:
      - '*'

jobs:
  lifecycle:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm ci

    - name: Audit depencdencies
      run: npm audit

    # Server Pipeline

    - name: Server - Lint
      run: npm run lint
      working-directory: server

    - name: Server - Test
      run: npm run test --if-present
      working-directory: server

    # Client Pipeline

    - name: Client - Lint
      run: npm run lint
      working-directory: client

    - name: Client - Test
      run: npm run test --if-present
      working-directory: client

    - name: Client - Build
      run: npm run build
      working-directory: client

    # Shared Pipeline

    - name: Shared - Lint
      run: npm run lint
      working-directory: shared

    - name: Shared - Test
      run: npm run test --if-present
      working-directory: shared